-- MySQL Script generated by MySQL Workbench
-- Sun Nov  1 22:31:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cit` DEFAULT CHARACTER SET utf8mb4 ;
USE `cit` ;

-- -----------------------------------------------------
-- Table `cit`.`cidadao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cit`.`cidadao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL UNIQUE,
  `senha` VARCHAR(32) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `cpf` CHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cit`.`denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cit`.`denuncia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` CHAR(1) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `logradouro` VARCHAR(40) NOT NULL,
  `referencia` VARCHAR(50) NULL,
  `uf` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(30) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cit`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cit`.`categoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cit`.`organizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cit`.`organizacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `cnpj` CHAR(14) NOT NULL UNIQUE,
  `uf` CHAR(2) NOT NULL,
  `cidade` VARCHAR(29) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cit`.`organizacao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cit`.`organizacao_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `organizacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_organizacao_usuario_organizacao1`
    FOREIGN KEY (`organizacao_id`)
    REFERENCES `cit`.`organizacao` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cit`.`denuncia_contribuicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cit`.`denuncia_contribuicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `anonimo` TINYINT(1) NOT NULL DEFAULT 0,
  `denuncia_id` INT NOT NULL,
  `cidadao_id` INT NULL,
  `organizacao_usuario_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_denuncia_contribuicao_denuncia1`
    FOREIGN KEY (`denuncia_id`)
    REFERENCES `cit`.`denuncia` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_contribuicao_cidadao1`
    FOREIGN KEY (`cidadao_id`)
    REFERENCES `cit`.`cidadao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_contribuicao_organizacao_usuario1`
    FOREIGN KEY (`organizacao_usuario_id`)
    REFERENCES `cit`.`organizacao_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cit`.`denuncia_contribuicao_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cit`.`denuncia_contribuicao_foto` (
  `url` VARCHAR(200) NOT NULL,
  `denuncia_contribuicao_id` INT NOT NULL,
  CONSTRAINT `fk_denuncia_contribuicao_foto_denuncia_contribuicao`
    FOREIGN KEY (`denuncia_contribuicao_id`)
    REFERENCES `cit`.`denuncia_contribuicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cit`.`denuncia_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cit`.`denuncia_has_categoria` (
  `denuncia_id` INT NOT NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`denuncia_id`, `categoria_id`),
  CONSTRAINT `fk_denuncia_has_categoria_denuncia1`
    FOREIGN KEY (`denuncia_id`)
    REFERENCES `cit`.`denuncia` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_has_categoria_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `cit`.`categoria` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cit`.`organizacao_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cit`.`organizacao_has_categoria` (
  `organizacao_id` INT NOT NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`organizacao_id`, `categoria_id`),
  CONSTRAINT `fk_organizacao_has_categoria_organizacao1`
    FOREIGN KEY (`organizacao_id`)
    REFERENCES `cit`.`organizacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizacao_has_categoria_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `cit`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
